version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: database_sts
    environment:
      MYSQL_DATABASE: temple_sean_db
      MYSQL_USER: temple_user
      MYSQL_PASSWORD: Cw4hA-9RZgf)
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: mysqld --sql_mode=""
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
  www:
    depends_on:
      - db
    image: ews
    container_name: website_sts
    volumes:
      - "./:/var/www/html"
    ports:
      - 3000:80
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_sts
    ports:
      - 3001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge